version: 2
updates:
  # --- Go modules ---
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(go)"
    labels:
      - "dependencies"
      - "go"
    rebase-strategy: "auto"

  # --- Docker images ---
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(docker)"
    labels:
      - "dependencies"
      - "docker"
    rebase-strategy: "auto"
