run:
  timeout: 10m
  go: "1.24"
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/kubeshark/tracer
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  golint:
    min-confidence: 0.8
  misspell:
