on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Linter

permissions:
  contents: read

jobs:
  golint:
    name: Golint
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.21'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            sudo \
            libpcap-dev \
            llvm \
            libbpf-dev \
            libelf-dev \
            linux-headers-$(uname -r)
          ./install-capstone.sh

      - name: Generate eBPF object files and Go bindings
        run: make bpf

      - name: Go lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=10m -v
          go-version: '^1.21'
