on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Linter

permissions:
  contents: read

jobs:
  golint:
    name: Golint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.22'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            sudo \
            curl \
            build-essential \
            xz-utils \
            libpcap-dev \
            clang \
            llvm \
            libbpf-dev \
            libelf-dev
          ./install-capstone.sh

      - name: Generate eBPF object files and Go bindings
        run: make bpf

      - name: Install go dependencies
        run: |
          go env -w GOPRIVATE=github.com/kubeshark/*
          go env -w GOPROXY=direct
          go mod download

      - name: Go lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=10m
          go-version: '^1.21'
